blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'



urlpatterns = [
    
    path('', views.all_blog, name='all_blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
    
]

joni1234/urls.py
from django.contrib import admin
from django.urls import path,include
from portfolio import views 
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title


# Create your models here.

portfolio/models.py
from django.db import models


class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    image = models. ImageField(upload_to= 'portfolio/images')
    url = models.URLField(blank=True)


    def __str__(self):
        return self.title


# Create your models here.

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blog(request):
    hi = Blog.objects.all()
    return render(request,'blog/blog.html',{'hello':hi})

def detail(request,blog_id):
    blog = get_object_or_404(Blog, pk =blog_id)
    return render(request, 'blog/detail.html',{'blog':blog})

# Create your views here.

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    website = Project.objects.all()
    return render(request, 'portfolio/home.html',{'joni':website})

# Create your views here.

blog/templates/blog/blog.html
{% extends 'portfolio/base.html' %}

{% block content %}


hello Bloggggggggg
<br>

<h2>Joni has written {{ hello.count }} blogs{{ blog.count|pluralize }} </h2>

{% for zakariya in hello %}
<a href="{% url 'blog:detail' zakariya.id %}"><h1>{{zakariya.title}}"</h1></a>
<p>{{zakariya.date|date:"D d M Y"}}</p>
<p>{{zakariya.description|striptags|truncatechars:100 }}</p>

{% if zakariya.url %}
<a href="{{zakariya.url}}">Read more</a>
{% endif %}


{% endfor %}

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

     


 

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>

{% block content %}{% endblock %} 

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block content %}





        <h2>joni portfolio new junaid1234-project local_settings.py  are settings.py</h2>
<br>

<a href="{% url 'blog:all_blog' %}">Blog</a>

<br>                                            

{% load static %}
<img src="{% static 'portfolio/make_up_1.jpeg' %}">

{% for zak in joni %}

<h1>{{zak.title}}</h1>
<p>{{zak.description}}</p>
<img src="{{zak.image.url}}" height= "500" width="500")>

{% if zak.url %}
<a href="{{ zak.url }}">Link</a>
{% endif %}

{% endfor %}

{% endblock %}



                                             